# Testing out the Linux Build to compare against Windows

name: Continuous Integration

on:

  push:
    branches:
      - master
      
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '.github/**'
      - '*.md'
    branches:
      - "master"

  workflow_dispatch:

jobs:
  Build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      SolutionName: Paulov.Bepinex.Framework
      ProjectClient: Paulov.Bepinex.Framework.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Restore all projects
      - name: dotnet Restore
        run: dotnet restore

      # Build the project
      - name: dotnet Build
        run: 
          dotnet build -c ${{ matrix.configuration }}
